### ISSUE TITLE
FATAL:  role "coss_user" does not exist

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/coss#307]
I've updated my repo to the current version of master and did a ```docker-compose up```. I've got the following error. Maybe there is a missing migration for the role?

```
~/development/coss/ master
❯ docker-compose up
Starting coss_memcache ...
Starting coss_memcache
Starting coss_db ...
Starting coss_db ... done
Starting coss_web_1 ...
Starting coss_web_1 ... done
Attaching to coss_memcache, coss_db, coss_web_1
db_1         | LOG:  database system was shut down at 2017-08-20 22:42:49 UTC
db_1         | LOG:  MultiXact member wraparound protections are now enabled
db_1         | LOG:  database system is ready to accept connections
db_1         | LOG:  autovacuum launcher started
db_1         | FATAL:  role "coss_user" does not exist
web_1        | Traceback (most recent call last):
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
web_1        |     self.connect()
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
web_1        |     self.connection = self.get_new_connection(conn_params)
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
web_1        |     connection = Database.connect(**conn_params)
web_1        |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
web_1        |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1        | psycopg2.OperationalError: FATAL:  role "coss_user" does not exist
web_1        |
web_1        |
web_1        | The above exception was the direct cause of the following exception:
web_1        |
web_1        | Traceback (most recent call last):
web_1        |   File "manage.py", line 12, in <module>
web_1        |     execute_from_command_line(sys.argv)
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
web_1        |     utility.execute()
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
web_1        |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
web_1        |     self.execute(*args, **cmd_options)
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
web_1        |     output = self.handle(*args, **options)
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 83, in handle
web_1        |     executor = MigrationExecutor(connection, self.migration_progress_callback)
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
web_1        |     self.loader = MigrationLoader(self.connection)
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
web_1        |     self.build_graph()
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 209, in build_graph
web_1        |     self.applied_migrations = recorder.applied_migrations()
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
web_1        |     self.ensure_schema()
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
web_1        |     if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor
web_1        |     return self._cursor()
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 229, in _cursor
web_1        |     self.ensure_connection()
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
web_1        |     self.connect()
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
web_1        |     six.reraise(dj_exc_type, dj_exc_value, traceback)
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
web_1        |     raise value.with_traceback(tb)
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
web_1        |     self.connect()
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
web_1        |     self.connection = self.get_new_connection(conn_params)
web_1        |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
web_1        |     connection = Database.connect(**conn_params)
web_1        |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
web_1        |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1        | django.db.utils.OperationalError: FATAL:  role "coss_user" does not exist
web_1        |
db_1         | FATAL:  role "coss_user" does not exist
```

**Comment by MichaelKohler** [comment]
```docker-compose build``` to install the latest requirements doesn't help either.

**Comment by akatsoulas** [comment]
@MichaelKohler can you try `docker-compose rm -fv` and then `docker-compose up`?

**Comment by MichaelKohler** [comment]
> @MichaelKohler can you try docker-compose rm -fv and then docker-compose up?

That worked. However now I can't properly review the mentioned PR. :/

**Comment by akatsoulas** [comment]
Since the proposed solution worked, I am closing this issue but not the relevant PR in order to spent some time to resolve this issue permanently.
